- name: Create Logstash directory
  win_file:
    path: "{{ logstash_dir }}"
    state: directory

- name: Check folder permissions for Logstash
  win_acl:
    path: "{{ logstash_dir }}"
    user: '{{ ansible_user }}'
    rights: ReadAndExecute
    type: allow

- name: Download Logstash
  win_get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-8.14.1-windows-x86_64.zip
    dest: C:\ELK\logstash\logstash-8.14.1.zip

- name: Unzip Logstash
  win_unzip:
    src: C:\ELK\logstash\logstash-8.14.1.zip
    dest: C:\ELK\logstash
    creates: C:\ELK\logstash\logstash-8.14.1

- name: Configure Logstash
  win_template:
    src: logstash.yml.j2
    dest: C:\ELK\logstash\logstash-8.14.1\config\logstash.yml

- name: Reload variables from group_vars/all.yml
  include_vars:
    file: group_vars/all.yml
  delegate_to: localhost

- name: Start Logstash service
  win_service:
    name: "{{ logstash_service_name }}"
    state: started

- name: Wait for Logstash to start
  win_uri:
    url: http://localhost:9600
    method: GET
    status_code: 200
    retries: 30
    delay: 10
    register: logstash_start_result
    until: logstash_start_result.status == 200
    retries: 5
    delay: 10
