- name: Check if Logstash service exists
  win_shell: Get-Service logstash* | Select-Object -ExpandProperty Name
  register: service_status
  ignore_errors: yes

- block:
    
  - name: Stop Logstash service
    win_service:
      name: "{{ service_status.stdout_lines[0] }}"
      state: stopped

  - name: Remove Logstash service
    win_shell: sc.exe delete "{{ service_status.stdout_lines[0] }}"
    ignore_errors: yes

  when: service_status.stdout_lines != []

- name: Create Logstash directory
  win_file:
    path: "{{ logstash_dir }}"
    state: directory

- name: Check folder permissions for Logstash
  win_acl:
    path: "{{ logstash_dir }}"
    user: '{{ ansible_user }}'
    rights: ReadAndExecute
    type: allow

- name: Download Logstash
  win_get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-8.14.1-windows-x86_64.zip
    dest: C:\ELK\logstash\logstash-8.14.1.zip

- name: Unzip Logstash
  win_unzip:
    src: C:\ELK\logstash\logstash-8.14.1.zip
    dest: C:\ELK\logstash
    creates: C:\ELK\logstash\logstash-8.14.1

- name: Configure Logstash
  win_template:
    src: logstash.yml.j2
    dest: C:\ELK\logstash\logstash-8.14.1\config\logstash.yml

- name: Create Logstash service using NSSM
  win_shell: |
    C:\Temp\nssm\nssm-2.24\win64\nssm.exe install Logstash "C:\ELK\logstash\logstash-8.14.1\bin\logstash.bat"


- name: Start Logstash service
  win_service:
    name: Logstash
    state: started
