- name: Check if Logstash service exists
  win_shell: Get-Service logstash* | Select-Object -ExpandProperty Name
  register: service_status
  ignore_errors: yes

- block:
    
  - name: Stop Logstash service
    win_service:
      name: "{{ service_status.stdout_lines[0] }}"
      state: stopped

  - name: Remove Logstash service
    win_shell: sc.exe delete "{{ service_status.stdout_lines[0] }}"
    ignore_errors: yes

  when: service_status.stdout_lines != []

- name: Create Logstash directory
  win_file:
    path: "{{ logstash_directory }}"
    state: directory

- name: Check folder permissions for Logstash
  win_acl:
    path: "{{ logstash_directory }}"
    user: '{{ ansible_user }}'
    rights: ReadAndExecute
    type: allow

- name: Download Logstash
  win_get_url:
    url: "{{ logstash_download_url }}"
    dest: "{{ logstash_zip_dest }}"

- name: Unzip Logstash
  win_unzip:
    src: "{{ logstash_zip_dest }}"
    dest: "{{ logstash_directory }}"
    creates: "{{ logstash_unzipped_dir }}"

- name: Configure Logstash
  win_template:
    src: logstash.yml.j2
    dest: "{{ logstash_config_path }}\\logstash.yml"

- name: Create Logstash service using NSSM
  win_shell: |
    {{ nssm_path }} install Logstash "{{ logstash_unzipped_dir }}\\bin\\logstash.bat"


- name: Start Logstash service
  win_service:
    name: Logstash
    state: started
