- name: Create Kibana directory
  win_file:
    path: C:\ELK\kibana
    state: directory

- name: Check folder permissions for Kibana
  win_acl:
    path: C:\ELK\kibana
    user: '{{ ansible_user }}'
    rights: ReadAndExecute
    type: allow

- name: Download Kibana
  win_get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-8.14.1-windows-x86_64.zip
    dest: C:\ELK\kibana\kibana-8.14.1.zip

- name: Unzip Kibana
  win_unzip:
    src: C:\ELK\kibana\kibana-8.14.1.zip
    dest: C:\ELK\kibana
    creates: C:\ELK\kibana\kibana-8.14.1

- name: create kibana enrollment token
  win_shell: |
    cmd /c C:\ELK\elasticsearch\elasticsearch-8.14.1\bin\elasticsearch-service-tokens create elastic/kibana my_token
  register: service_token

- name: Extract the service token from the output
  set_fact:
    extracted_token: "{{ service_token.stdout | regex_search('=\\s*(.*)', '\\1') | first | trim }}"

- name: save output of service_token
  lineinfile:
    path: group_vars/all.yml
    regexp: '^service_token:'
    line: "service_token_extracted: '{{ extracted_token }}'"
  delegate_to: localhost

- name: Configure Kibana
  win_template:
    src: kibana.yml.j2
    dest: C:\ELK\kibana\kibana-8.14.1\config\kibana.yml

- name: Start Kibana
  win_shell: |
    Start-Process "C:\ELK\kibana\kibana-8.14.1\bin\kibana.bat" -NoNewWindow
  args:
    executable: powershell.exe
  async: 0
  poll: 0
