# Check if nssm is needed for Kibana and logstash to run as service
- name: Check if NSSM is installed
  win_shell: |
    Get-Command "{{ nssm_path }}"
  register: nssm_installed_result

- block:
  
  - name: Create Temp directory
    win_file:
      path: C:\Temp
      state: directory
  
  - name: Check folder permissions for Temp
    win_acl:
      path: C:\Temp
      user: '{{ ansible_user }}'
      rights: ReadAndExecute
      type: allow
  
  - name: Download NSSM
    win_get_url:
      url: "{{ nssm_download_url }}"
      dest: "{{ nssm_zip_dest }}"
  
  - name: Unzip NSSM
    win_unzip:
      src: "{{ nssm_zip_dest }}"
      dest: "{{ nssm_unzip_dest }}"
      creates: "{{ nssm_path }}"
  
  when: nssm_installed_result.rc != 0
