## Check if nssm is needed for Kibana and logstash to run as service
#- name: Check if NSSM is installed
#  win_shell: |
#    Get-Command "nssm.exe"
#  register: nssm_installed_result
#
#- block:
#  
#  - name: Create Temp directory
#    win_file:
#      path: C:\Temp
#      state: directory
#  
#  - name: Check folder permissions for Temp
#    win_acl:
#      path: C:\Temp
#      user: '{{ ansible_user }}'
#      rights: ReadAndExecute
#      type: allow
#  
#  - name: Download NSSM
#    win_get_url:
#      url: "https://nssm.cc/release/nssm-2.24.zip"
#      dest: C:\Temp\nssm.zip
#  
#  - name: Unzip NSSM
#    win_unzip:
#      src: C:\Temp\nssm.zip
#      dest: C:\Temp\nssm
#      creates: C:\Temp\nssm\nssm.exe
#  
#  when: nssm_installed_result.rc != 0
